### ISSUE TITLE
Giving an empty arg on cli errors

### ISSUE THREAD

**Issue by UnderTheCarpet** [jeff-hykin/nix_version_search_cli#2]
```
# nvs
⠋ fetchingerror: Uncaught TypeError: Cannot read properties of undefined (reading 'parse')
    return command.parse(["--help"].concat(Deno.args));
                   ^
    at _Command.actionHandler (file:///nix/store/v2fsasnkp9xbmcz2vl89h2c38p6mlyq8-source/build_helper/main.bundle.js:208462:20)
    at _Command.execute (file:///nix/store/v2fsasnkp9xbmcz2vl89h2c38p6mlyq8-source/build_helper/main.bundle.js:3705:18)
    at async _Command.parseCommand (file:///nix/store/v2fsasnkp9xbmcz2vl89h2c38p6mlyq8-source/build_helper/main.bundle.js:3582:14)
    at async file:///nix/store/v2fsasnkp9xbmcz2vl89h2c38p6mlyq8-source/build_helper/main.bundle.js:208452:15
```

Awesome tool!

**Comment by jeff-hykin** [comment]
Alright should be fixed with `v1.3.1`, thanks for reporting!
