### ISSUE TITLE
Flake installation not working

### ISSUE THREAD

**Issue by KDanisme** [jeff-hykin/nix_version_search_cli#5]
After installing from the repos flake, im getting a lot of warnings and errors.

```
nvs nodejs
warning: Use of deprecated "Deno.writeAllSync()" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
⠋ fetchingwarning: Use of deprecated "Deno.customInspect" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
√ finished fetch
? Which Package [type OR press enter OR use arrow keys] › warning: Use of deprecated "Deno.stdin.rid" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.                 : Event-driven I/O framework for the V8 JavaScript engine
warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
Failed getting version info from one of the sources (nixhub.io):I/O framework for the V8 JavaScript engine
    Error: Looks like www.nixhub.io has updated, meaning this CLI tool needs to be updated (issue finding list $("main ul"))
  nodejs-slim_latest                             : Event-driven I/O framework for the V8 JavaScript engine
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'filter')JavaScript engine
      if (versions.filter((each2) => each2.version.startsWith(versionPrefix)).length == 0) {aScript engine
                   ^js-repl                      :
    at file:///nix/store/l462xk35gch0qkwmh75lif6xmk8dljzp-source/build_helper/main.bundle.js:212747:20
    at eventLoopTick (ext:core/01_core.js:63:7)
```
    
   After some cleanup
   ```warning: Use of deprecated "Deno.writeAllSync()" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
warning: Use of deprecated "Deno.customInspect" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
warning: Use of deprecated "Deno.stdin.rid" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
Failed getting version info from one of the sources (nixhub.io):I/O framework for the V8 JavaScript engine
      Error: Looks like www.nixhub.io has updated, meaning this CLI tool needs to be updated (issue finding list $("main ul"))
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'filter')JavaScript engine
      if (versions.filter((each2) => each2.version.startsWith(versionPrefix)).length == 0) {aScript engine
                   ^js-repl                      :
    at file:///nix/store/l462xk35gch0qkwmh75lif6xmk8dljzp-source/build_helper/main.bundle.js:212747:20
    at eventLoopTick (ext:core/01_core.js:63:7)

```
The deprecation warnings ill be happy to submit a pr to fix, but the exception itself and the update to the cli message i have no clue about.

Thanks for the cool tool regardless

**Comment by jeff-hykin** [comment]
Thanks for reporting! Looks like nix.io updated their site.

I published nvs `v1.3.8` just now and it should go back to working as expected. Also I added a bit better protection so that these warnings dont completely block the other valid responses from other sources.

Let me know if you've still got an issue on your end
